# Generated by Django 3.1.3 on 2020-12-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
